# Generated by Django 3.2.2 on 2021-07-31 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_department', models.CharField(max_length=50, null=True, verbose_name='部门编号')),
                ('department', models.CharField(max_length=50, null=True, verbose_name='部门名称')),
                ('Details', models.TextField(max_length=1000, null=True, verbose_name='部门简介')),
            ],
            options={
                'verbose_name': ('部门信息',),
                'verbose_name_plural': '部门信息',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_position', models.CharField(max_length=50, null=True, verbose_name='工作岗位编号')),
                ('position', models.CharField(max_length=50, null=True, verbose_name='工作岗位')),
                ('Details', models.TextField(max_length=1000, null=True, verbose_name='工作岗位职责')),
                ('ID_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Other_Dao.department', verbose_name='归属部门编号')),
            ],
            options={
                'verbose_name': ('工作岗位信息',),
                'verbose_name_plural': '工作岗位信息',
            },
        ),
    ]
