# Generated by Django 3.2.2 on 2021-08-01 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Other_Dao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='ID_department',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='部门编号'),
        ),
        migrations.AlterField(
            model_name='position',
            name='ID_position',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='工作岗位编号'),
        ),
    ]
