# Generated by Django 3.2.2 on 2021-08-01 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('UserProfiles_app', '0002_alter_userprofile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.TextField(max_length=500, null=True, verbose_name='任务内容')),
                ('closing_day', models.DateTimeField(verbose_name='截止日期')),
                ('notice_day', models.DateTimeField(auto_now_add=True, verbose_name='通知日期')),
                ('status', models.CharField(choices=[('已完成', '已完成'), ('未处理', '未处理')], default='未处理', max_length=20, verbose_name='完成状态')),
                ('Distributor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Distributor_UserProfile', to='UserProfiles_app.userprofile', verbose_name='分配人')),
                ('people_work', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='people_work_UserProfile', to='UserProfiles_app.userprofile', verbose_name='指定员工')),
            ],
            options={
                'verbose_name': ('任务清单',),
                'verbose_name_plural': '任务清单',
            },
        ),
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.TextField(max_length=1000, null=True, verbose_name='申报信息')),
                ('apply_day', models.DateField(auto_now_add=True, verbose_name='申报时间')),
                ('process_status', models.CharField(choices=[('未处理', '未处理'), ('已同意', '已同意'), ('已拒绝', '已拒绝')], default='未处理', max_length=20, null=True, verbose_name='处理状态')),
                ('process_day', models.DateField(auto_now=True, verbose_name='处理时间')),
                ('applicant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applicant_UserProfile', to='UserProfiles_app.userprofile')),
                ('hander', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Apply_hander_UserProfile', to='UserProfiles_app.userprofile')),
            ],
            options={
                'verbose_name': ('申报表',),
                'verbose_name_plural': '申报表',
            },
        ),
        migrations.CreateModel(
            name='Advise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advise', models.TextField(max_length=1000, null=True, verbose_name='建议')),
                ('submit_time', models.DateField(auto_now_add=True, verbose_name='提交时间')),
                ('status', models.CharField(choices=[('未处理', '未处理'), ('已同意', '已同意'), ('已拒绝', '已拒绝')], default='未处理', max_length=20, verbose_name='处理状态')),
                ('feedback', models.TextField(max_length=1000, null=True, verbose_name='反馈')),
                ('process_day', models.DateField(auto_now=True, verbose_name='处理时间')),
                ('hander', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Advise_hander_UserProfile', to='UserProfiles_app.userprofile', verbose_name='处理人')),
                ('proposer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proposer_UserProfile', to='UserProfiles_app.userprofile')),
            ],
            options={
                'verbose_name': ('投递建议',),
                'verbose_name_plural': '投递建议',
            },
        ),
    ]
