# Generated by Django 3.2.2 on 2021-08-01 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfiles_app', '0003_alter_userprofile_user'),
        ('Work_Dao', '0003_auto_20210801_0901'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_time', models.DateTimeField(verbose_name='提醒时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('note', models.TextField(max_length=1000, null=True, verbose_name='便签内容')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator_UserProfile', to='UserProfiles_app.userprofile', verbose_name='创建人')),
            ],
            options={
                'verbose_name': ('便签',),
                'verbose_name_plural': '便签',
            },
        ),
    ]
