# Generated by Django 3.2.2 on 2021-08-01 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Work_Dao', '0004_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='status',
            field=models.CharField(choices=[('已完成', '已完成'), ('未处理', '未处理')], default='未处理', max_length=20, verbose_name='完成状态'),
        ),
    ]
