# Generated by Django 3.2.2 on 2021-08-01 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Work_Dao', '0005_note_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='reminder_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='提醒时间'),
        ),
    ]
