# Generated by Django 3.2.2 on 2021-08-01 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Work_Dao', '0006_alter_note_reminder_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='modify_time',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='创建时间'),
        ),
    ]
