# Generated by Django 3.2.2 on 2021-08-02 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Work_Dao', '0008_auto_20210802_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='task_list',
            name='modify_day',
            field=models.DateTimeField(auto_now=True, verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='task_list',
            name='closing_day',
            field=models.DateTimeField(verbose_name='截止时间'),
        ),
        migrations.AlterField(
            model_name='task_list',
            name='notice_day',
            field=models.DateTimeField(auto_now_add=True, verbose_name='通知时间'),
        ),
    ]
