# Generated by Django 3.2.2 on 2021-08-03 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Work_Dao', '0009_auto_20210802_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='reply',
            field=models.TextField(max_length=1000, null=True, verbose_name='回复'),
        ),
    ]
