# Generated by Django 3.2.2 on 2021-07-31 15:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Other_Dao', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=135, null=True, verbose_name='姓名')),
                ('gender', models.CharField(blank=True, choices=[('male', '男'), ('female', '女')], max_length=135, null=True, verbose_name='性别')),
                ('ID_number', models.CharField(max_length=18, null=True, verbose_name='身份证号码')),
                ('political_landscape', models.CharField(blank=True, max_length=50, null=True, verbose_name='政治面貌')),
                ('address', models.CharField(blank=True, max_length=135, null=True, verbose_name='住址')),
                ('phone', models.CharField(max_length=11, null=True, verbose_name='手机号码')),
                ('education', models.CharField(blank=True, max_length=50, null=True, verbose_name='学历')),
                ('enter_time', models.DateField(auto_now_add=True, verbose_name='入职时间')),
                ('base_salary', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='基本薪资')),
                ('bank_card', models.CharField(max_length=50, null=True, verbose_name='银行卡号')),
                ('notes', models.TextField(blank=True, max_length=500, null=True, verbose_name='备注')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='最后修改时间')),
                ('ID_department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Other_Dao.department', verbose_name='归属部门编号')),
                ('ID_position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Other_Dao.position', verbose_name='岗位编号')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': ('扩展信息',),
                'verbose_name_plural': '扩展信息',
            },
        ),
    ]
