# Generated by Django 3.2.2 on 2021-08-01 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Other_Dao', '0002_auto_20210801_0936'),
        ('UserProfiles_app', '0003_alter_userprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='ID_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Other_Dao.department', verbose_name='归属部门编号'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='ID_position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Other_Dao.position', verbose_name='岗位编号'),
        ),
    ]
