# Generated by Django 3.2.2 on 2021-08-03 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfiles_app', '0004_auto_20210801_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('男', '男'), ('女', '女')], max_length=135, null=True, verbose_name='性别'),
        ),
    ]
