# Generated by Django 3.2.2 on 2021-07-31 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('UserProfiles_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sign_status', models.CharField(choices=[('签到成功', '签到成功'), ('暂未签到', '暂未签到')], default='暂未签到', max_length=20, verbose_name='签到状态')),
                ('sign_time', models.DateField(auto_now_add=True, verbose_name='签到时间')),
                ('my_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserProfiles_app.userprofile', unique=True, verbose_name='提出者')),
            ],
            options={
                'verbose_name': ('签到',),
                'verbose_name_plural': '签到',
            },
        ),
    ]
