# Generated by Django 3.2.2 on 2021-08-03 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_project', '0004_alter_sign_my_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sign',
            name='sign_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='签到时间'),
        ),
    ]
